---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "example-custom-strategy"
    name: "example-custom-strategy"
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "example-custom-strategy"
    name: "example-custom-strategy"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "example-custom-strategy:latest"
    resources: {}
    source:
      git:
        ref: "master"
        uri: "https://github.com/sdirbach/openshift-examples-custom-builder.git"
      type: Git
    strategy:
      customStrategy:
        from:
          kind: "DockerImage"
          name: "openshift/origin-custom-docker-builder"
        exposeDockerSocket: true
